[tool.poetry]
name = "helloworld"
version = "0.0.1"
description = ""
authors = ["ChooChooCthulhu <mikemanx8@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.9"
kivy = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
